### ISSUE TITLE
Speech recognition tasks

### ISSUE THREAD

**Issue by rafaelvp-db** [Lightning-AI/lightning-transformers#247]
## 🚀 Feature

Creating a new type of tasks in Lightning Transformers for Speech Recognition (ASR), e.g. Wav2Vec2, etc.

### Pitch

Currently to train or finetune ASR models using Hugging Face, some extra/boilerplate code is needed (preprocessing, creating vocabularies etc). At the same time, currently ASR is not available in Lightning Transformers. Would make it much easier to train such models using DDP, Horovod etc.

### Alternatives

No alternatives AFAIK

### Additional context

I've tried to start creating a brand new ASR task (based on the existing tasks for question answering, text classification etc), but struggling a bit with some aspects for instance: how to make this as flexible/reusable as possible, general doubts about Lightning etc. If anyone is willing to review / help / work together: https://github.com/rafaelvp-db/lightning-transformers/tree/feature/asr. I don't have a lot of experience with Lightning so bear with me :)

**Comment by SeanNaren** [comment]
This is amazing!! It seems you've merged in recent changes to simplify the API, I hope it helps in the process of creating the task.

If you have any questions let me know; if you open the PR I can help to contribute if I get time :)

**Comment by rafaelvp-db** [comment]
Awesome @SeanNaren! Will do :)
