### ISSUE TITLE
Continued ViT support 

### ISSUE THREAD

**Issue by tanmoyio** [Lightning-AI/lightning-transformers#250]
## 🚀 Feature

Lightning-transformers is still nlp specific, I want to work on ViT support. 
@SeanNaren

**Comment by SeanNaren** [comment]
That would be so awesome! getting some CV stuff in here would be awesome :) 

Seems you're up for contributing! More than happy to help get this integrated

**Comment by tanmoyio** [comment]
@SeanNaren can we start tasks here ? I want to integrate, segmentation, detection and other models in vision also.

**Comment by SeanNaren** [comment]
Oh nice! don't worry about making an issue to capture all the tasks you want to create, just go for it :)

**Comment by tanmoyio** [comment]
@Nexer8 yes, detection, segmentation and other type or vision tasks
