### ISSUE TITLE
Shuffle support

### ISSUE THREAD

**Issue by mahnerak** [Lightning-AI/lightning-transformers#272]
After looking the codebase I've discovered there's no shuffling while training.
Is there any reason for it?

https://github.com/Lightning-AI/lightning-transformers/blob/f439c954fd085499ddde4ed27f927ba70d079595/lightning_transformers/core/data.py#L174-L181

**Comment by Borda** [comment]
@SeanNaren, mind checking this out? :otter:

**Comment by Borda** [comment]
closing in favor of #298
