### ISSUE TITLE
How to fix ModuleNotFoundError: No module named 'habana_frameworks.torch'

### ISSUE THREAD

**Issue by zolekode** [Lightning-AI/lightning-transformers#282]
## ❓ Questions and Help

I am getting this error after following the instructions on installing habana for pytorch and running my script.
- OS: Ubuntu 20.04
- Packaging: Pip
Anyone has an idea on how to resolve it?

**Comment by Borda** [comment]
Hi, I believe you should be using the Habana docker image where all needed libraries shall be already prepared for you: `vault.habana.ai/gaudi-docker/1.5.0/ubuntu20.04/habanalabs/pytorch-installer-1.11.0:latest`
