### ISSUE TITLE
pip installation issues

### ISSUE THREAD

**Issue by omerarshad** [Lightning-AI/lightning-transformers#285]
Facing difficulty installing using  `pip install lightning-transformers`,

INFO: pip is looking at multiple versions of numpy, and it keeps on searching for hours.

Any solution?

**Comment by turian** [comment]
This is pip backtracking and it SUCKS. The only solution I know is to pin a numpy dependency. I've heard of tools like poetry that may solve this, but I haven't used them.

**Comment by Borda** [comment]
@omerarshad, can you give us some more details about your local configuration (OS, Python version, and if you used Conda env.)?

**Comment by turian** [comment]
@omerarshad Can you please post the full log including all the backtracking?

It's important for us to share this with pypi upstream, because they are actively trying to squash this backtracking nonsense.

**Comment by techthiyanes** [comment]
Kindly install from the source where you won't face any issues.
git clone https://github.com/PyTorchLightning/lightning-transformers.git
cd lightning-transformers
pip install .
