### ISSUE TITLE
Lightning 1.8 breaks lightning-transformers

### ISSUE THREAD

**Issue by juliusfrost** [Lightning-AI/lightning-transformers#300]
## 🐛 Bug

Errors:
LightningDeprecationWarning: `LightningDataModule.on_save_checkpoint` was deprecated in v1.6 and will be removed in v1.8. Use `state_dict` instead.
LightningDeprecationWarning: `LightningDataModule.on_load_checkpoint` was deprecated in v1.6 and will be removed in v1.8. Use `load_state_dict` instead.
### To Reproduce

Run any lightning-transformers DataModule in the trainer.

#### Code sample

These two methods in particular cause the errors in `lightning_transformers\core\data.py`.
```py
    def on_save_checkpoint(self, checkpoint: Dict[str, Any]) -> None:
        checkpoint["tokenizer"] = self.tokenizer

    def on_load_checkpoint(self, checkpoint: Dict[str, Any]) -> None:
        self.tokenizer = checkpoint["tokenizer"]
```

**Comment by Borda** [comment]
This shall be addressed by ongoing work #297
